FROM michaxm/base-extended
RUN \
    echo "===> add webupd8 repository..."  && \
    echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list  && \
    echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list  && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886  && \
    apt-get update  && \
    \
    \
    echo "===> install Java"  && \
    echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections  && \
    echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections  && \
    DEBIAN_FRONTEND=noninteractive  apt-get install -y --force-yes oracle-java8-installer oracle-java8-set-default  && \
    \
    \
    echo "===> clean up... (not apt)"  && \
    rm -rf /var/cache/oracle-jdk8-installer

RUN ln -s /usr/lib/jvm/java-8-oracle /usr/lib/jvm/default
ENV JAVA_HOME /usr/lib/jvm/default
ENV PATH $PATH:$JAVA_HOME/bin

# tired of searching for java path assumptions
RUN mkdir -p /usr/java && ln -s /usr/lib/jvm/default /usr/java/default
